name: Build Windows App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.9
        pip install PyQtWebEngine==5.15.6
        pip install plotly
        pip install pillow
        pip install PyQt5 pandas numpy matplotlib opencv-python openpyxl pyinstaller
        pyinstaller --name DanioAnalyzer --windowed main_window.py
    - uses: actions/upload-artifact@v4
      with:
        name: DanioAnalyzer
        path: dist/DanioAnalyzer
